name: proj4dart
description: Proj4dart is a Dart library to transform point coordinates from one coordinate system to another, including datum transformations (Dart version of proj4js/proj4js).
version: 3.0.0
homepage: https://github.com/maRci002/proj4dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  mgrs_dart: ^3.0.0
  wkt_parser: ^2.0.0
  meta: ^1.3.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.15
